#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 13 11:58:04 2017

@author: emg
"""

import pandas as pd

df = pd.read_csv('/Users/emg/Programming/GitHub/subreddit-visuals/tidy_data/mods/td-mod-hist.csv', index_col=0)

current = timeline[timeline.loc[last][timeline.loc[last] > 0].index]

names = current.columns

df = df[df['name'].isin(names)]

perms = df['permissions'].value_counts()

labels = pd.Series(perms.index)
labels.drop(2, inplace=True)
labels = labels.str.split(',', expand=True)



cols = list(labels.loc[0].str.lstrip('+-'))
labels.columns = cols

for name in cols:
    labels[name] = labels[name].str.startswith('+')

labels.sort_values(cols, ascending=False, inplace=True)


'''
+access,-config,+flair,+mail,+posts,-wiki    1929
+access,-config,-flair,-mail,+posts,-wiki     384
+all                                          317
+access,+config,+flair,+mail,+posts,+wiki     303
+access,-config,+flair,+mail,+posts,+wiki     248
+access,-config,-flair,+mail,+posts,-wiki     176
-access,-config,-flair,-mail,+posts,+wiki     103
+access,+config,+flair,+mail,+posts,-wiki      80
+access,+config,-flair,+mail,+posts,+wiki      57
+access,-config,+flair,-mail,+posts,-wiki      23
+access,+config,+flair,-mail,+posts,-wiki       9
-access,-config,-flair,-mail,-posts,-wiki       8
+access,+config,+flair,-mail,+posts,+wiki       6
+access,-config,+flair,-mail,+posts,+wiki       2
'''



+access,+config,+flair,+mail,+posts,+wiki     303
+access,-config,+flair,+mail,+posts,+wiki     248
+access,-config,-flair,+mail,+posts,-wiki     176
-access,-config,-flair,-mail,+posts,+wiki     103

{'+access,-config,-flair,-mail,+posts,-wiki':2,
                 '+access,-config,+flair,+mail,+posts,-wiki':3,
                 '+all':4,
                 
                 
                 '+access,+config,+flair,+mail,+posts,+wiki':5,
                 '+access,-config,+flair,+mail,+posts,+wiki':6,
                 '+access,-config,-flair,+mail,+posts,-wiki':7,
                 '-access,-config,-flair,-mail,+posts,+wiki':8}

colours = ('white','chocolate','slateblue','seagreen','black',
           'tomato','olive','aquamarine','orchid')

def prep_df(df):
    '''subset df into required columns and types
    to construct timeline df'''
    df['date'] = pd.to_datetime(df['date']).dt.normalize()
    df['pubdate'] = pd.to_datetime(df['pubdate']).dt.normalize()
    after_dict = make_after_dict(df)
    df['after'] = pd.to_datetime(df['pubdate'].map(lambda x:
                                    after_dict[x])).dt.normalize()
    df['perm_level'] = df['permissions'].map(
            {'+access,-config,-flair,-mail,+posts,-wiki':2,
                 '+access,-config,+flair,+mail,+posts,-wiki':3,
                 '+all':4,
                 '+access,+config,+flair,+mail,+posts,+wiki':5,
                 '+access,-config,+flair,+mail,+posts,+wiki':6,
                 '+access,-config,-flair,+mail,+posts,-wiki':7,
                 '-access,-config,-flair,-mail,+posts,+wiki':8}
            ).fillna(1)
    df.sort_values(['date','pubdate'], inplace=True)
    df.drop_duplicates(['name','date'], keep='last', inplace=True)
    df.set_index('name', inplace=True, drop=False)
    df = df[['name','date','pubdate','after','perm_level']]
    return df

def set_cmap():
    colours = ('white','chocolate','slateblue','seagreen','black',
               'tomato','olive','aquamarine','orchid')
    cmap = LinearSegmentedColormap.from_list('Custom', colours, len(colours))
    return cmap

def td_split_plot():
    '''create timeline subplots for former and current td mods'''
    last = timeline.index[-1]
    current = timeline[timeline.loc[last][timeline.loc[last] > 0].index]
    former = timeline[timeline.loc[last][timeline.loc[last] == 0].index]
    
    fig, (ax1, ax2) = plt.subplots(2,1) #, figsize=(9,13))
    
    g1 = sns.heatmap(former, cmap=set_cmap(),cbar=False, ax=ax1)
    start, end = g1.get_ylim()
    g1.set_yticks(np.arange(start, end, 30))
    g1.set_yticklabels(list(timeline.index.strftime('%Y-%m'))[::-30])
    g1.tick_params(axis='x',which='both', labelbottom='off')
    
    g1.set_title('TD Former Moderators')
    g1.set_ylabel('Date')
    
    g2 = sns.heatmap(current, cmap=set_cmap(), ax=ax2)
    start, end = g2.get_ylim()
    g2.set_yticks(np.arange(start, end, 30))
    g2.set_yticklabels(list(timeline.index.strftime('%Y-%m'))[::-30])
    g2.tick_params(axis='x',which='both', labelbottom='off')
    
    g2.set_title('TD Current Moderators')
    g2.set_xlabel('TD Moderators')
    g2.set_ylabel('Date')
    
    colorbar = ax2.collections[0].colorbar
    colorbar.set_ticks(np.arange(0.5, len(colours)+0.5, 1))
    colorbar.set_ticklabels(['not present', 'other perm types',
                             '+ access, posts', '+ access, flair, mail, posts',
                             'all',
                             '+access, config, flair, mail, posts, wiki',
                             '+access, flair, mail, posts, wiki',
                             '+access, mail, posts',
                             '+posts, wiki'])
    colorbar.ax.set_title('Permission type')
    
    plt.tight_layout()
    plt.savefig('/Users/emg/Programming/GitHub/subreddit-visuals/figures/td-timeline-split-V-8perms.png')


